---
title: "TP Biochimie BAB2 Q1"
author: 
  - name: "Guillaume Gégo"
  - name: "Raphaël Deroux"
  - name: "Emeline Derycke"
date: "03/11/2020"
output: html_document
---
***
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
## **Atelier 1:** Les Protéines
  
### Introduction
  
#### Qu'est-ce qu'une protéine?
Une protéine est une macromolécule polymère dont les monomères sont les acides aminés (aa). Les protéines sont les composés organiques les plus abondants dans les cellules: ils constituent plus de 50% de leur masse sèche. Elles sont directement codées à partir des gènes (transcription: 1 gène code pour une ou plusieurs protéines) et synthétisées par les ribosomes à partir d'acides aminés simples (traduction) t elles permettent le fonctionnement de toute cellule vivante. 
  
#### Rôles des protéines
Qu'elles soient transportrices, hormonales, structurales, co-factrices, signalétiques, régulatrices, enzymatiques ou autres, les protéines forment un protéome de plus d'1 million de protéines. Ces protéines présentent différent niveaux de structuration: primaire, secondaire, tertiaire et quaternaire.
  
#### Les niveaux de structuration
* **La structure primaire**: agencement covalent des acides aminés entre eux. L'ordre des acides aminés en partant de l'extrémité N-terminale vers l'extrémité C-terminale définit la nature de la protéine produite.
  
* **La structure secondaire**: conformations **localisées** et **répétées** le long de la chaîne polypeptidique.Elles sont de 4 types majeurs :les hélices alpha, les feuillets plissés bêta, les tonneaux bêta et les tournants bêta. Ces 4 exemples sont des **"motifs"** et l'association de motifs donnera ensuite des **"domaines"**, qui sont les unités de structure de la structure tertiaire. La fonction de la structure secondaire est de catalyser le reploiement tridimentionnel de la protéine par le biais des motifs qui s'assemblent en domaines, constituant ainsi de véritables noyaux de nucléation qui catalysent le folding de la chaîne d'aa. Les propriétés de ceniveau de structuration sont directement dues à la structure du lien peptidique (plan et polaire) et de son lien amide à entonoir structural. Ce niveau de structuration n'est stabilisé que par des liens hydrogène.
  
* **La structure tertiaire**: agencement des structures secondaires (domaines) dans l'espace tridimentionnel. Ce niveau de structuration optionnel n'est stabilisé que par des liens de faible énergie tels que:
  + Les interaction hydrophobes et hydrophiles (V.D.W.)
  + Les liens hydrogène
  + Les interactions dipôles-charges
  + Les liasons ioniques
Les boucles inter-domaines portent souvent l'activité de la protéine!
  
* **La structure quaternaire**: association dans l'espace tridimentionnel des différentes chaines polypeptidiques. Ce niveau de structuration n'est stabilisé que par des liens de faible énergie (voir structure tertiaire), MAIS il est rigidifié par liens disulfure S-S covalents (en dehors du milieu réducteur de la cellule). Ce niveau d'organisation apporte deux "avantages" majeures:
  + Présence de structures particulières: cavités centrales (hémoglobine)
  + Phénomène de coopérativité: les sous-unités interagissent entre elle de telle sorte que la modification conformationnel de l'une d'entre elles engendre l'augmentation de l'efficacité des autres sous-unités. Si une protéine a une structure quaternaire (plus d'une sous-unité) et présente des propriétés de coopérativité, elle est dite **allostérique**.
  
#### Dénaturation des protéines
Toutes ses structures sont stabilisées par des liasons de forte et de faible énergie. Il est bien évidemment possible de **dénaturer** (briser la structure de) la protéine en utilisant diverses méthodes:
  
* Chaleur (ex: coagulation de l'albumine du blanc d'oeuf).
* Rayons UV et radiations ionisantes.
* Variations de pH.
* Détergents.
* Solvants organiques.
* Solution d'urée ou de guanidine.
* Simple dilution ou agitation.
  
  
### But de la manipulation
Cette manipulation est segmentée en deux parties:
* La séparation de protéines par colonne de chromatographie: cette partie a pour but de séparer 3 molécules (Blue dextran, Hémoglobine et Ferycianine de K) selon leur taille. Pour ce faire, on utilise un gel de dextrane à différent domaines de réticulation: le **Sephadex** (phase stationnaire), constamment hydraté par une solution de NaCl 0.9% (9g de NaCl pour 1L d'eau ≃ solution physiologique).
*
  
### Matériel
* NaCl 0.9% (1L).
* Sephadex G50 et G100.
* Blue dextran 2000 (2000 000Da) 2mg/ml (100ml).
* Hémoglobine (65 000 Da) 5mg/ml (100ml).
* Ferrycianide de potassium  (329 Da)	2mg/ml (100ml).
* Verres à pied et béchers.
* Colonne de chromatographie (2/ groupe), ouate, bouchon, tuyau, pipette pasteur.
  
### Méthode 

#### Séparation de protéines par colonne de chromatographie
Deux solution de Sephadex préalablement préparées furent mises à notre disposition: une G50 et une G100. Un solution supplémentaire de NaCl 0,9 % fut aussi réalisée afin de nous permettre de constamment hydrater le Sephadex
  
Ensuite, il fallut remplir 2 colonnes de verre à 3/4 de leur capacité avec le G50 pour l'une et le G100 pour l'autre. La sédimentation du séphadex étant nécessaire, nous laissâmes le robinet ouvert, pour ensuite retirer, à l'aide d'une pipette pasteur, l'excès de NaCl 0.9% surnageant le Sephadex pour n'en laisser qu'un milimètre. Après avoir refermé le robinet, nous délivrâmes circulairement un volume de 150 µl de chaque protéine le long de la colonne en prenant gare à ne pas perturber la surface du gel.
  
La masse en dalton des différents composés est la suivante:
  
* **Blue dextran (2.000.000 Da):** ce composé devrait aller rapidement vers le bas de la colonne (plus lourd).
* **Hémoglobine (65.000 Da):** ce composé ira plus lentement.
* **Ferycianine de K (329 Da):** ce composé sera assez lent et restera probablement un moment dans le quart supérieur de la colonne de chromatographie.

De grosses protéines dépassant la limite d'exclusion pourront être observées, descendant à la même vitesse dans les deux Sephadex.
A contrario, de petites protéines pourront être observées, avec une progression néanmoins plus rapide dans le Sephadex G50. En effet, les "billes" étant plus grosses, les petites protéines passeront au travers plus aisément.

L'ouverture du robinet permit ensuite la pénétration de la phase stationnaire (Sephadex) par les différentes protéines (élution), tandis que la phase mobile (NaCl) était constamment renouvelée pour permettre l'élution protéique. Une fois l'élution achevée, nous recueillâmes le tampon mélangé aux protéines dans un verre à pied afin de comparer les volumes d'élution des différentes protéines à travers le G50 et le G100.

Cette étape achevées, une courbe étalon fut élaborée sur excel à partir des datapoints recueillis.

#### Séparation de protéines par colonne de chromatographie
  
### Résultats

  
### Discussion

  
### Conclusion


### Bibliographie


